
[[_modules]]
= Modules
:subproject-base: {rootdir}/subprojects/griffon-icomoonicons-
:java-source: /src/main/java/
:groovy-source: /src/main/groovy/
:package-base: org/codehaus/griffon/runtime/
:numbered:

The following sections display all bindings per module. Use this information to
successfully override a binding on your own modules or to troubleshoot a module
binding if the wrong type has been applied by the Griffon runtime.

== JavaFX

Module name: `icomoonicons-javafx-groovy`

Depends on: `javafx-groovy`

[source,java,options="nowrap"]
----
include::{subproject-base}javafx-groovy{groovy-source}{package-base}/javafx/icomoonicons/IcoMoonIconsJavaFXGroovyModule.java[tags=bindings,indent=0]
----

The following nodes will become available on a Groovy View

[options="2*,header"]
|===
| Node        | Type
| icoMoonIcon | `{api_link_icomoonicon_javafx}`
|===

== Swing

Module name: `icomoonicons-swing-groovy`

Depends on: `swing-groovy`

[source,java,options="nowrap"]
----
include::{subproject-base}swing-groovy{java-source}{package-base}/swing/icomoonicons/IcoMoonIconsSwingGroovyModule.java[tags=bindings,indent=0]
----

The following nodes will become available on a Groovy View

[options="2*,header"]
|===
| Node        | Type
| icoMoonIcon | `{api_link_icomoonicon_swing}`
|===

Both `icoMoonIcon` Nodes support the following properties

icon:: The name of the icon, such as `github` or `twitter`.
size:: The size of the icon. Either `16` or `32`.

